list(APPEND ACPICA_SOURCES
    source/components/utilities/utaddress.c
    source/components/utilities/utalloc.c
    source/components/utilities/utascii.c
    source/components/utilities/utbuffer.c
    source/components/utilities/utcache.c
    source/components/utilities/utclib.c
    source/components/utilities/utcopy.c
    source/components/utilities/utdebug.c
    source/components/utilities/utdecode.c
    source/components/utilities/utdelete.c
    source/components/utilities/uterror.c
    source/components/utilities/uteval.c
    source/components/utilities/utexcep.c
    source/components/utilities/utglobal.c
    source/components/utilities/uthex.c
    source/components/utilities/utids.c
    source/components/utilities/utinit.c
    source/components/utilities/utlock.c
    source/components/utilities/utmath.c
    source/components/utilities/utmisc.c
    source/components/utilities/utmutex.c
    source/components/utilities/utnonansi.c
    source/components/utilities/utobject.c
    source/components/utilities/utosi.c
    source/components/utilities/utownerid.c
    source/components/utilities/utpredef.c
    source/components/utilities/utprint.c
    source/components/utilities/utresdecode.c
    source/components/utilities/utresrc.c
    source/components/utilities/utstate.c
    source/components/utilities/utstring.c
    source/components/utilities/utstrsuppt.c
    source/components/utilities/utstrtoul64.c
    source/components/utilities/uttrack.c
    source/components/utilities/utuuid.c
    source/components/utilities/utxface.c
    source/components/utilities/utxferror.c
    source/components/utilities/utxfinit.c
    source/components/utilities/utxfmutex.c)
